before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq debhelper curl php5-cli php5-curl

script:
  - dpkg-buildpackage -us -uc -b
  - sudo dpkg -i ../php-composer*.deb
  - composer
